language: ruby
rvm:
- 2.3.7
sudo: false
script: bundle exec rake deploy
exclude:
- vendor
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master