title: अथातो घुमक्कड़ जिज्ञासा
description: Eternal Curiousity Of Traveler's Mind.
url: 'https://ghumakkad.github.io/'
# Site/SEO settings
logo: assets/images/compass.png
email: pccfrmvns@gmail.com
permalink: /:year/:month/:day/:title/
google_analytics: UA-11391792-8
baseurl: "/blog"
lang: en_US
twitter_username: pccofvns
default_img: /assets/images/pp.jpeg
# Profile settings
name: Prashant C Chaturvedi
author: pccofvns
profile_img: assets/images/me.png
profile: I am a software engineer, based in Delhi, India. I was born in Sonbhadra, raised in Varanasi/Allahabad and graduated from Lucknow.
social:
  name: Prashant C Chaturvedi
  github: https://github.com/pccofvns
  facebook: https://www.facebook.com/pccofvns
  linkedin: https://www.linkedin.com/in/pccofvns/
  twitter: https://twitter.com/@pccofvns
  instagram: https://instagram.com/pccofvns/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-autoprefixer
  - jekyll-asciidoc
  - jekyll-mentions
  - jemoji
  - jekyll-avatar
  - jekyll-readme-index
  - jekyll-seo-tag
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - _screenshots
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor

# Pagination
paginate: 5
paginate_path: "/blog/page-:num"

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

# Sass
sass:
  style: compressed

readme_index:
  enabled:          true
  remove_originals: true

jekyll-mentions:
  base_url: https://twitter.com

asciidoc:
  ext: asciidoc,adoc
  processor: asciidoctor
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font